"use client";
import { useState } from "react";

import { addCategory, type TAddCategory } from "@/actions/category/category";
import Button from "@/shared/components/ui-v2/button";
import Popup from "@/shared/components/ui-v2/popup";

import GroupCategory from "../../forms/groupCategory";

type TProps = {
  onReset: () => void;
};

const AddCategoryGroup = ({ onReset }: TProps) => {
  const [showWindow, setShowWindow] = useState<boolean>(false);
  const defaultGroupData: TAddCategory = {
    id: "",
    name: "",
    slug: "", // Will be auto-generated by addCategory action from name
    description: undefined,
    createdAt: new Date(),
    updatedAt: undefined,
  };
  const [errorMsg, setErrorMsg] = useState<string | undefined>("");
  const [buttonDisabled, setButtonDisabled] = useState(false);
  const [groupCategoryData, setGroupCategory] =
    useState<TAddCategory>(defaultGroupData);

  const handleAddGroup = async () => {
    const { name } = groupCategoryData;

    // Validate name (required, min 3 characters as per schema)
    if (!name || name.trim() === "") {
      setErrorMsg("Category name is required!");
      return;
    }
    if (name.trim().length < 3) {
      setErrorMsg("Category name must be at least 3 characters!");
      return;
    }

    setButtonDisabled(true);
    setErrorMsg("");

    // Prepare data for addCategory action
    const categoryData: TAddCategory = {
      id: "",
      name: name.trim(),
      slug: "", // Will be auto-generated by addCategory action
      description: groupCategoryData.description?.trim() || undefined,
      createdAt: new Date(),
      updatedAt: undefined,
    };

    const { res, error } = await addCategory(categoryData);

    if (res) {
      setGroupCategory(defaultGroupData);
      setButtonDisabled(false);
      setErrorMsg("");
      setShowWindow(false);
      onReset();
    } else {
      setButtonDisabled(false);
      const errorMessage = error && "Can't Insert it to Database!";
      setErrorMsg(errorMessage);
    }
  };

  return (
    <div>
      <Button className="text-sm py-1" onClick={() => setShowWindow(true)}>
        Add Group
      </Button>
      {showWindow && (
        <Popup
          content={
            <GroupCategory
              errorMsg={errorMsg}
              data={groupCategoryData}
              onChange={setGroupCategory}
            />
          }
          isLoading={buttonDisabled}
          onCancel={() => setShowWindow(false)}
          onClose={() => setShowWindow(false)}
          onSubmit={handleAddGroup}
          title="Add Category Group"
        />
      )}
    </div>
  );
};

export default AddCategoryGroup;
