'use client';

import { useState } from 'react';

import {
  addCategory,
  updateCategory,
  deleteCategory,
  TGetAllCategories,
  TAddCategory,
  TUpdateCategory,
} from '@/actions/category/category';
import GroupCategory from '@/domains/admin/components/forms/groupCategory';
import Button from '@/shared/components/ui-v2/button';
import Popup from '@/shared/components/ui-v2/popup';

import AddCategory from './addCategory';
import Category from './category';
import CategoryOptions from './categoryOptions';

type TProps = {
  data: TGetAllCategories & { parentId?: string | null };
  categories: (TGetAllCategories & { parentId?: string | null })[];
  onReset: () => void;
};

const initialCategory: TAddCategory = {
  id: '',
  name: '',
  slug: '',
  description: undefined,
  createdAt: new Date(),
  updatedAt: undefined,
};

const RowCatGroup = ({ data, categories, onReset }: TProps) => {
  const { id: groupId, name } = data;
  const [showOptions, setShowOptions] = useState(false);
  const [showEdit, setShowEdit] = useState(false);
  const [showDelete, setShowDelete] = useState(false);
  const [showAddCategory, setShowAddCategory] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | undefined>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [groupCategoryData, setGroupCategoryData] = useState<TAddCategory>({
    id: data.id,
    name: data.name,
    slug: data.slug,
    description: data.description || undefined,
    createdAt: data.createdAt,
    updatedAt: data.updatedAt || undefined,
  });
  const [addCategoryData, setAddCategoryData] = useState<TAddCategory>(initialCategory);

  // ---------------------- FUNCTIONS ----------------------
  const handleUpdateGroup = async () => {
    const updatedData: TUpdateCategory = { id: groupId };

    if (groupCategoryData.name !== data.name) {
      updatedData.name = groupCategoryData.name;
    }

    if (groupCategoryData.description !== (data.description || undefined)) {
      updatedData.description = groupCategoryData.description;
    }

    // Only update if there are actual changes
    if (!updatedData.name && !updatedData.description) {
      setShowEdit(false);
      setErrorMsg('');
      return;
    }

    setIsLoading(true);
    setErrorMsg('');
    const response = await updateCategory(updatedData);

    if ('res' in response && response.res) {
      setShowEdit(false);
      setIsLoading(false);
      setErrorMsg('');
      onReset();
    } else {
      setIsLoading(false);
      const errorMessage =
        'error' in response
          ? typeof response.error === 'string'
            ? response.error
            : String(response.error)
          : "Can't update category";
      setErrorMsg(errorMessage);
    }
  };

  const handleDelete = async () => {
    setIsLoading(true);
    setErrorMsg('');
    const response = await deleteCategory(groupId);

    if ('error' in response && response.error) {
      setErrorMsg(response.error);
      setIsLoading(false);
      return;
    }
    if ('res' in response && response.res) {
      setErrorMsg('');
      setIsLoading(false);
      setShowDelete(false);
      onReset();
    }
  };

  const handleAddCategory = async () => {
    if (!addCategoryData.name || addCategoryData.name.trim() === '') {
      setErrorMsg('Category Name should not be empty');
      return;
    }
    if (addCategoryData.name.trim().length < 3) {
      setErrorMsg('Category name must be at least 3 characters');
      return;
    }

    const categoryData: TAddCategory = {
      id: '',
      name: addCategoryData.name.trim(),
      slug: '', // Will be auto-generated by addCategory action
      description: addCategoryData.description?.trim() || undefined,
      createdAt: new Date(),
      updatedAt: undefined,
    };

    setIsLoading(true);
    setErrorMsg('');
    const response = await addCategory(categoryData);

    if ('error' in response && response.error) {
      setIsLoading(false);
      setErrorMsg(response.error);
      return;
    }
    if ('res' in response && response.res) {
      setAddCategoryData(initialCategory);
      setErrorMsg('');
      setIsLoading(false);
      setShowAddCategory(false);
      onReset();
    }
  };

  return (
    <div className='flex flex-wrap text-sm justify-between p-3 pl-5 items-center'>
      <span className='inline-block w-[200px] text-gray-700 text-sm'>{name}</span>
      <div className='flex gap-2'>
        <Button size='md' onClick={() => setShowOptions(true)}>
          Options / Specifications
        </Button>
        <Button size='md' onClick={() => setShowAddCategory(true)}>
          Add Category
        </Button>
      </div>
      <div className='flex gap-2'>
        <Button size='md' onClick={() => setShowEdit(true)}>
          Edit
        </Button>
        <Button size='md' onClick={() => setShowDelete(true)}>
          Delete
        </Button>
      </div>
      {!!categories.length && (
        <div className='min-w-full flex flex-col mt-3'>
          {categories?.map(
            (cat) =>
              cat.parentId === data.id && (
                <Category
                  data={cat}
                  key={cat.id}
                  subCategories={categories.filter((c) => c.parentId === cat.id)}
                  onReset={onReset}
                />
              )
          )}
        </div>
      )}
      {showOptions && (
        <Popup
          content={<CategoryOptions categoryID={groupId} categoryName={name} />}
          isLoading={false}
          onClose={() => setShowOptions(false)}
          onCancel={() => setShowOptions(false)}
          onSubmit={() => setShowOptions(false)}
          title=''
        />
      )}
      {showAddCategory && (
        <Popup
          content={
            <AddCategory data={addCategoryData} errorMsg={errorMsg} onChange={setAddCategoryData} />
          }
          width='360px'
          isLoading={isLoading}
          onCancel={() => setShowAddCategory(false)}
          onClose={() => setShowAddCategory(false)}
          onSubmit={() => handleAddCategory()}
          title='Add Category'
        />
      )}
      {showEdit && (
        <Popup
          content={
            <GroupCategory
              errorMsg={errorMsg || ''}
              data={groupCategoryData}
              onChange={setGroupCategoryData}
            />
          }
          isLoading={isLoading}
          onCancel={() => setShowEdit(false)}
          onClose={() => setShowEdit(false)}
          onSubmit={() => handleUpdateGroup()}
          title={`Updating Group: ${data.name}`}
        />
      )}
      {showDelete && (
        <Popup
          content={
            <div className='w-full px-5 pt-5 pb-10 flex gap-4 flex-col items-center justify-center text-center'>
              <span>Are you sure?</span>
              <span>{errorMsg}</span>
            </div>
          }
          isLoading={isLoading}
          width='400px'
          onCancel={() => setShowDelete(false)}
          onClose={() => setShowDelete(false)}
          onSubmit={() => handleDelete()}
        />
      )}
    </div>
  );
};

export default RowCatGroup;
